# This workflow Builds the UFS Short Range Weather APP
name: Build SRWA

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - rrfs_ci 
    types: 
      - labeled 

# Use a default login shell which loads intel/oneapi/setvars.sh, and lmod path 
defaults:
  run:
    shell: bash -l {0}

jobs:

  Clone_SRWA:
    name: Clone Repo
    if: ${{ github.event.label.name == 'ci-aws-intel-build' }}
    runs-on: self-hosted 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ufs-srweather-app-${{ github.run_id }}

      - name: Verify Branch 
        run: |
          git branch -a
  
  Build_SRWA:
    name: Build SRWA 
    if: ${{ github.event.label.name == 'ci-aws-intel-build' }}
    runs-on: self-hosted
    needs: Clone_SRWA

    steps:
      - name: Build Short Range Weather App using test/build.sh
        run: |
          cd ufs-srweather-app-${{ github.run_id }}
          ./manage_externals/checkout_externals
          cd test/
          ./build.sh aws 2>&1 | tee build_test.out

  Build_Status:
    name: Check Build Sucess or Failure 
    runs-on: self-hosted 
    if: ${{ github.event.label.name == 'ci-aws-intel-build' }}
    needs: [ Clone_SRWA, Build_SRWA ]
    
    steps:
      - name: Get build status
        run: |
          cd ufs-srweather-app-${{ github.run_id }}/test/
          status=`tail -1 build_test.out |cut -d ' ' -f 3-`
          if [ $status == PASS ]; then
            exit 0
          else 
            exit 1
          fi

